In [1]:
# Numpy Methods
import numpy as np

In [2]:
# argmin, argmax, argsort
# mean, median, mode, standard deviation, variance
# ravel, flatten
# hstack, vstack

In [3]:
numbers = np.random.randint(100,1000,50)

In [4]:
np.max(numbers)

964

In [5]:
# index of maximum number
np.argmax(numbers)

35

In [6]:
np.min(numbers)

120

In [7]:
# index of minimum number
np.argmin(numbers)

14

In [8]:
numbers[14], numbers[35]

(120, 964)

In [9]:
# index of numbers to be sorted
np.argsort(numbers)

array([14, 44,  0, 46, 30, 15, 39, 29, 34, 38, 31, 49, 43, 20, 41, 37, 11,
        9, 17,  7, 26,  4, 40, 28, 32, 27, 23, 22, 12, 47, 25, 16,  6, 19,
       42, 18,  2, 36, 21,  3,  1,  5, 10, 24, 13, 33, 45,  8, 48, 35], dtype=int64)

In [11]:
np.sort(numbers)

array([120, 129, 130, 151, 176, 177, 191, 208, 213, 216, 222, 229, 248,
       255, 295, 295, 318, 329, 367, 369, 372, 385, 432, 461, 462, 508,
       512, 536, 553, 566, 568, 595, 612, 625, 669, 701, 761, 773, 791,
       804, 832, 850, 901, 911, 913, 916, 917, 918, 945, 964])

In [12]:
# Average
np.mean(numbers)

507.81999999999999

In [13]:
# Mid value
np.median(numbers)

485.0

In [15]:
# Standard deviation - how much data deviates from the standard (average)
np.std(numbers)

271.68648770227793

In [16]:
# Variance - square of standard deviation
np.var(numbers)

73813.547600000005

In [17]:
x = np.array([[5,6,7,4,6,7],[12,14,34,21,45,11],[12,151,24,26,31,19]])

In [18]:
x

array([[  5,   6,   7,   4,   6,   7],
       [ 12,  14,  34,  21,  45,  11],
       [ 12, 151,  24,  26,  31,  19]])

In [19]:
x.shape

(3, 6)

In [21]:
x.reshape(2,9)

array([[  5,   6,   7,   4,   6,   7,  12,  14,  34],
       [ 21,  45,  11,  12, 151,  24,  26,  31,  19]])

In [24]:
x.reshape(2,-1)

array([[  5,   6,   7,   4,   6,   7,  12,  14,  34],
       [ 21,  45,  11,  12, 151,  24,  26,  31,  19]])

In [25]:
# convert data to 1D
x.flatten()

array([  5,   6,   7,   4,   6,   7,  12,  14,  34,  21,  45,  11,  12,
       151,  24,  26,  31,  19])

In [28]:
# convert data to 1D
x.ravel()

array([  5,   6,   7,   4,   6,   7,  12,  14,  34,  21,  45,  11,  12,
       151,  24,  26,  31,  19])

In [30]:
x = x.reshape(2,9)

In [31]:
x

array([[  5,   6,   7,   4,   6,   7,  12,  14,  34],
       [ 21,  45,  11,  12, 151,  24,  26,  31,  19]])

In [33]:
np.hstack(x)

array([  5,   6,   7,   4,   6,   7,  12,  14,  34,  21,  45,  11,  12,
       151,  24,  26,  31,  19])

In [34]:
np.vstack(x)

array([[  5,   6,   7,   4,   6,   7,  12,  14,  34],
       [ 21,  45,  11,  12, 151,  24,  26,  31,  19]])

In [37]:
# Transpose of data
x.T

array([[  5,  21],
       [  6,  45],
       [  7,  11],
       [  4,  12],
       [  6, 151],
       [  7,  24],
       [ 12,  26],
       [ 14,  31],
       [ 34,  19]])