# Numpy Introduction

In [1]:
import numpy as np

In [2]:
# ways to create array using numpy

# 1. Use np.array()
x1 = np.array([2,3,4,5,67,8,8,89,12,13,5])

In [3]:
x1[0]

2

In [4]:
x1[0:3]

array([2, 3, 4])

In [5]:
x1[-1]

5

In [6]:
type(x1[1])

numpy.int32

In [7]:
# 2. Use np.linspace()
x2 = np.linspace(1,10)

In [8]:
x2

array([  1.        ,   1.18367347,   1.36734694,   1.55102041,
         1.73469388,   1.91836735,   2.10204082,   2.28571429,
         2.46938776,   2.65306122,   2.83673469,   3.02040816,
         3.20408163,   3.3877551 ,   3.57142857,   3.75510204,
         3.93877551,   4.12244898,   4.30612245,   4.48979592,
         4.67346939,   4.85714286,   5.04081633,   5.2244898 ,
         5.40816327,   5.59183673,   5.7755102 ,   5.95918367,
         6.14285714,   6.32653061,   6.51020408,   6.69387755,
         6.87755102,   7.06122449,   7.24489796,   7.42857143,
         7.6122449 ,   7.79591837,   7.97959184,   8.16326531,
         8.34693878,   8.53061224,   8.71428571,   8.89795918,
         9.08163265,   9.26530612,   9.44897959,   9.63265306,
         9.81632653,  10.        ])

In [9]:
len(x2)

50

In [16]:
x2 = np.linspace(10,100,retstep=True, num=20)

In [17]:
x2

(array([  10.        ,   14.73684211,   19.47368421,   24.21052632,
          28.94736842,   33.68421053,   38.42105263,   43.15789474,
          47.89473684,   52.63157895,   57.36842105,   62.10526316,
          66.84210526,   71.57894737,   76.31578947,   81.05263158,
          85.78947368,   90.52631579,   95.26315789,  100.        ]),
 4.7368421052631575)

In [14]:
# 3. Use np.zeros() or np.ones()
x3 = np.zeros(5)

In [15]:
x3

array([ 0.,  0.,  0.,  0.,  0.])

In [18]:
x3 = np.zeros((3,3))

In [19]:
x3

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [20]:
x3.ndim

2

In [21]:
x3.shape

(3, 3)

In [22]:
x4 = np.ones(5)

In [23]:
x4

array([ 1.,  1.,  1.,  1.,  1.])

In [24]:
x4 = np.ones((4,4))

In [25]:
x4

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [26]:
# 4. Use np.identity()
x5 = np.identity(5)

In [27]:
x5

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [32]:
# 5. Use random numbers
x6 = np.random.random()

In [33]:
x6

0.20700710213842743

In [36]:
x6 = np.random.random((3,3))

In [37]:
x6

array([[ 0.55707742,  0.56384439,  0.62659067],
       [ 0.24612121,  0.64767347,  0.05053259],
       [ 0.23920256,  0.24553757,  0.97466942]])

In [38]:
x7 = np.random.randint(10,20)

In [39]:
x7

18

In [40]:
# from 10 to 100...we will get 25 random numbers
x7 = np.random.randint(10,100,25)

In [41]:
x7

array([70, 26, 17, 96, 83, 14, 26, 66, 58, 80, 54, 36, 97, 79, 74, 59, 29,
       71, 12, 47, 46, 14, 11, 17, 33])

In [42]:
# 6. Use np.arange()
x8 = np.arange(2,20)

In [43]:
x8

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])